.TH "coordinate" 3 "Mon Mar 20 2017" "VC - Snake Bite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coordinate
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBdirection\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int direction"

.SS "int x"

.SS "int y"


.SH "Author"
.PP 
Generated automatically by Doxygen for VC - Snake Bite from the source code\&.
