.TH "E:/ProProjects/C/VCTicTacToe/main.c" 3 "Mon Mar 20 2017" "VCTicTacToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/ProProjects/C/VCTicTacToe/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <conio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <windows\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmenu\fP ()"
.br
.ti -1c
.RI "void \fBgo\fP (int n)"
.br
.ti -1c
.RI "void \fBstart_game\fP ()"
.br
.ti -1c
.RI "void \fBcheck_draw\fP ()"
.br
.ti -1c
.RI "void \fBdraw_board\fP ()"
.br
.ti -1c
.RI "void \fBplayer_first\fP ()"
.br
.ti -1c
.RI "void \fBput_X_O\fP (char ch, int pos)"
.br
.ti -1c
.RI "void \fBgotoxy\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBmain\fP ()"
.br
.ti -1c
.RI "int \fBmake2\fP ()"
.br
.ti -1c
.RI "int \fBmake4\fP ()"
.br
.ti -1c
.RI "int \fBposswin\fP (int p)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBboard\fP [10] = {2,2,2,2,2,2,2,2,2,2}"
.br
.ti -1c
.RI "int \fBturn\fP = 1"
.br
.ti -1c
.RI "int \fBflag\fP = 0"
.br
.ti -1c
.RI "int \fBplayer\fP"
.br
.ti -1c
.RI "int \fBcomp\fP"
.br
.ti -1c
.RI "COORD \fBcoord\fP ={0,0}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void check_draw ()"

.PP
Definition at line 224 of file main\&.c\&.
.SS "void draw_board ()"

.PP
Definition at line 235 of file main\&.c\&.
.SS "void go (int n)"

.PP
Definition at line 159 of file main\&.c\&.
.SS "void gotoxy (int x, int y)"

.PP
Definition at line 24 of file main\&.c\&.
.SS "void main ()"

.PP
Definition at line 31 of file main\&.c\&.
.SS "int make2 ()"

.PP
Definition at line 68 of file main\&.c\&.
.SS "int make4 ()"

.PP
Definition at line 83 of file main\&.c\&.
.SS "void menu ()"

.PP
Definition at line 38 of file main\&.c\&.
.SS "void player_first ()"

.PP
Definition at line 168 of file main\&.c\&.
.SS "int posswin (int p)"

.PP
Definition at line 96 of file main\&.c\&.
.SS "void put_X_O (char ch, int pos)"

.PP
Definition at line 259 of file main\&.c\&.
.SS "void start_game ()"

.PP
Definition at line 196 of file main\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int board[10] = {2,2,2,2,2,2,2,2,2,2}"
Tic Tac Toe Game Developed by Adari Vamsi --------------Version 1\&.1--------------- Grab the Input device to Play Harder Adari Vamsi Visual Efx 
.PP
Definition at line 11 of file main\&.c\&.
.SS "int comp"

.PP
Definition at line 12 of file main\&.c\&.
.SS "COORD coord ={0,0}"

.PP
Definition at line 21 of file main\&.c\&.
.SS "int flag = 0"

.PP
Definition at line 12 of file main\&.c\&.
.SS "int player"

.PP
Definition at line 12 of file main\&.c\&.
.SS "int turn = 1"

.PP
Definition at line 12 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VCTicTacToe from the source code\&.
